<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>a-hdps</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="4a-hdps_files/libs/clipboard/clipboard.min.js"></script>
<script src="4a-hdps_files/libs/quarto-html/quarto.js"></script>
<script src="4a-hdps_files/libs/quarto-html/popper.min.js"></script>
<script src="4a-hdps_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="4a-hdps_files/libs/quarto-html/anchor.min.js"></script>
<link href="4a-hdps_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="4a-hdps_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="4a-hdps_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="4a-hdps_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="4a-hdps_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="4a-hdps_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="4a-hdps_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content page-columns page-full" id="quarto-document-content">



<section id="step-1-proxy-sources" class="level1 page-columns page-full">
<h1>Step 1: Proxy sources</h1>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Load saved data
</div>
</div>
<div class="callout-body-container callout-body">
<p>We saved <code>analytic3cycles.RData</code> in <a href="NHANES.qmd">Appendix</a>. This contained the following datasets:</p>
<ul>
<li><code>data.merged</code> = merged data from 3 cycles,</li>
<li><code>data.complete</code> = complete case merged data,</li>
<li><code>dat.proxy.long</code> = only proxy information</li>
</ul>
</div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-1_d27addaa21a9c7505c302149ebc60e35">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/analytic3cycles.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-with-investigator-specified-variables" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="data-with-investigator-specified-variables">Data with investigator-specified variables</h2>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Data: part 1
</div>
</div>
<div class="callout-body-container callout-body">
<p>We will work with the <code>data.complete</code> data for the investigator-specified information.</p>
</div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-2_029d1f48f00d203d3341069a10a225a6">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>analytic <span class="ot">&lt;-</span> data.complete</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> analytic<span class="sc">$</span>id</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>outcome <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(analytic<span class="sc">$</span>diabetes <span class="sc">==</span> <span class="st">"Yes"</span>) </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>exposure <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(analytic<span class="sc">$</span>obese <span class="sc">==</span> <span class="st">"Yes"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>domain <span class="ot">&lt;-</span> <span class="st">"dx"</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>analytic.dfx <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(idx, exposure, outcome, domain))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>We prepare the minimal analytic data only with the following 4 information:</p>
<ul>
<li>identifying information (<code>idx</code>)</li>
<li>exposure (<code>obese</code>)</li>
<li>outcome (<code>diabetes</code>)</li>
<li>domain of the codes (<code>dx</code>). In this example we only have prescription domain (1 domain <code>dx</code>)</li>
</ul>
</div></div></section>
<section id="proxy-data" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="proxy-data">Proxy data</h2>
<section id="identify-the-data-dimensions-proxy-sources" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="identify-the-data-dimensions-proxy-sources">Identify the data dimensions (proxy sources)</h3>
<p>In this example we only have <mark>prescription domain</mark> (1 domain <code>dx</code> of ICD-10-CM code). Hence <mark><span class="math inline">\(p = 1\)</span></mark> in this exercise.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>NHANES Questionnaire collects information on: (a) dietary supplements, (b) nonprescription antacids, (c) prescription medications, and (d) preventive aspirin use.</p>
</div></div></section>
<section id="define-a-covariate-assessment-period-cap" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="define-a-covariate-assessment-period-cap">Define a covariate assessment period (CAP)</h3>
<p>We only collect proxy information from a well-defined CAP. In our case, it was <mark><span class="math inline">\(30\)</span> days</mark>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>NHANES asked “In the past 30 days, have you used or taken medication for which a prescription is needed? Do not include prescription vitamins or minerals you may have already told me about.”</p>
</div></div><div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Data: part 2
</div>
</div>
<div class="callout-body-container callout-body">
<p>We will work with the merge proxy data (ICD-10 codes) from 3 cycles: <code>dat.proxy.long</code>.</p>
</div>
</div>
</section>
<section id="omit-duplicated-information" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="omit-duplicated-information">Omit duplicated information</h3>

<div class="no-row-height column-margin column-container"><div class="">
<p>We need to delete codes that could be close proxies of exposure and/or outcome, or other investigator specified covariates we have already selected in step0.</p>
</div></div><div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-3_0e616bdd851505bd55ca2bd2a1f01ab3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dat.proxy.long <span class="ot">&lt;-</span> <span class="fu">subset</span>(dat.proxy.long, </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                         icd10 <span class="sc">!=</span> <span class="st">"E66"</span>) <span class="co"># Overweight and obesity</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>dat.proxy.long <span class="ot">&lt;-</span> <span class="fu">subset</span>(dat.proxy.long, </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                         icd10 <span class="sc">!=</span> <span class="st">"O24"</span>) <span class="co"># Gestational diabetes mellitus</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>dat.proxy.long <span class="ot">&lt;-</span> <span class="fu">subset</span>(dat.proxy.long, </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                         icd10 <span class="sc">!=</span> <span class="st">"E10"</span>) <span class="co"># Type 1 diabetes mellitus</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>dat.proxy.long <span class="ot">&lt;-</span> <span class="fu">subset</span>(dat.proxy.long, </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                         icd10 <span class="sc">!=</span> <span class="st">"E11"</span>) <span class="co"># Type 2 diabetes mellitus</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<ul>
<li>We delete codes associated with exposure and outcome.</li>
<li>Same should be done for any other proxies that may have duplicating information compared to the investigator-specified covariates.</li>
</ul>
</div></div></section>
<section id="long-format-proxy-data" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="long-format-proxy-data">Long format proxy data</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-4_3fd4579a74cd87feb730e5973a0995f4">

</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Here is an example of 3 digit codes for 1 patient with subject ID “100001”. We create the same for all patients.</p>
</div></div><div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-5_5d4385e9b013e814a61bf8077eaf53ca">
<div class="cell-output-display">

<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> ID </th>
   <th style="text-align:left;"> ICD 10 codes (3 digit) </th>
   <th style="text-align:left;"> Description </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 100001 </td>
   <td style="text-align:left;width: 3cm; text-align:center;"> F33 </td>
   <td style="text-align:left;"> Major depressive disorder, recurrent </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 100001 </td>
   <td style="text-align:left;width: 3cm; text-align:center;"> I10 </td>
   <td style="text-align:left;"> Hypertension </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 100001 </td>
   <td style="text-align:left;width: 3cm; text-align:center;"> M62 </td>
   <td style="text-align:left;"> Muscle spasm </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 100001 </td>
   <td style="text-align:left;width: 3cm; text-align:center;"> F32 </td>
   <td style="text-align:left;"> Major depressive disorder, single episode </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 100001 </td>
   <td style="text-align:left;width: 3cm; text-align:center;"> M25 </td>
   <td style="text-align:left;"> Joint disorder/pain </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 100001 </td>
   <td style="text-align:left;width: 3cm; text-align:center;"> K21 </td>
   <td style="text-align:left;"> Gastro-esophageal reflux disease </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 100001 </td>
   <td style="text-align:left;width: 3cm; text-align:center;"> M79 </td>
   <td style="text-align:left;"> musculoskeletal pain conditions </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 100001 </td>
   <td style="text-align:left;width: 3cm; text-align:center;"> R12 </td>
   <td style="text-align:left;"> Heartburn </td>
  </tr>
</tbody>
</table>

</div>
</div>
</section>
</section>
<section id="merge-proxy-data-with-analytic-data" class="level2">
<h2 class="anchored" data-anchor-id="merge-proxy-data-with-analytic-data">Merge Proxy data with Analytic data</h2>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Merged Data: parts 1 and 2
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>We will work with the merge proxy data with analytic data.</li>
<li>That will provide us with the IDs (<code>idx</code>) of the subject that have proxy (ICD-10) information associated with them.</li>
</ul>
</div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-6_2b1d9497d2f4b3b9df64da63d983e938">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(dplyr) </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dfx <span class="ot">&lt;-</span> <span class="fu">merge</span>(analytic.dfx, proxy.var.long, <span class="at">by =</span> <span class="st">"idx"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dfx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     idx exposure outcome domain icd10
1 100001        1       0     dx   F33
2 100001        1       0     dx   M79
3 100001        1       0     dx   F32
4 100001        1       0     dx   R12
5 100001        1       0     dx   M79
6 100001        1       0     dx   K21</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>basetable <span class="ot">&lt;-</span> dfx <span class="sc">%&gt;%</span> <span class="fu">select</span>(idx, exposure, outcome) <span class="sc">%&gt;%</span> <span class="fu">distinct</span>()</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>patientIds <span class="ot">&lt;-</span> basetable<span class="sc">$</span>idx</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(patientIds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7585</code></pre>
</div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-7_8115e9c7fa154f5dd655981f21ceb338">

</div>
</section>
</section>
<section id="step-2-empirical" class="level1 page-columns page-full">
<h1>Step 2: Empirical</h1>
<p>Based on the merged dataset, we identify which patients were linked in both databases. Using those IDs, we want to sort the list of candidate empirical covariates.</p>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-8_7ba94423bff78784a300517e6104e940">

</div>
<section id="sort-by-prevalence" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sort-by-prevalence">Sort by prevalence</h2>
<p>Check out the frequency of each codes:</p>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-9_17dbb8760e1efbf18cfe96c2757a5e7b">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">icd10 =</span> <span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(dfx<span class="sc">$</span>icd10), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">count =</span> <span class="fu">sort</span>(<span class="fu">table</span>(dfx<span class="sc">$</span>icd10), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-10_f663537dfe5752f45a5ab9a28bd4e577">
<div class="cell-output-display">

<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>ICD10 Code Frequencies</caption>
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;"> ICD10 Code </th>
   <th style="text-align:right;font-weight: bold;"> Count </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> I10 </td>
   <td style="text-align:right;width: 5em; "> 5742 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> E78 </td>
   <td style="text-align:right;width: 5em; "> 2965 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> F32 </td>
   <td style="text-align:right;width: 5em; "> 1135 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> F41 </td>
   <td style="text-align:right;width: 5em; "> 1090 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> K21 </td>
   <td style="text-align:right;width: 5em; "> 911 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> M79 </td>
   <td style="text-align:right;width: 5em; "> 870 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> E03 </td>
   <td style="text-align:right;width: 5em; "> 807 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> M54 </td>
   <td style="text-align:right;width: 5em; "> 772 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> G47 </td>
   <td style="text-align:right;width: 5em; "> 697 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> J45 </td>
   <td style="text-align:right;width: 5em; "> 626 </td>
  </tr>
</tbody>
</table>

</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Only top 10 prevalent codes are shown.</p>
</div></div><p>However, some may be associated with lower counts (e.g., less than 20).</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Restrictions
</div>
</div>
<div class="callout-body-container callout-body">
<p>Candidate empirical covariates list is constrained by</p>
<ol type="1">
<li>their prevalence of codes. <mark>Only top <code>n</code> covariates with highest prevalence</mark> would be chosen.</li>
<li>analysts absolutely need to get rid of the codes that have <mark>zero variance</mark> (e.g., everyone has the code, or nobody has it).</li>
<li>codes associated with <mark>very low prevalence</mark> are also numerically problematic for further analyses.</li>
</ol>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>We choose <code>n = 200</code> [for (1)] as it was proposed in the original algorithm. In reality, this is not necessary to be so restrictive. Parts (2) and (3) are more likely and addressed by the following restriction: At least <code>min_num_patients</code> number of patients need to have that code to be selected in the list.</p>
</div></div><p>If there were more dimensions, separate list of candidate empirical covariates would be identified.</p>
</section>
<section id="choose-granularity" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="choose-granularity">Choose Granularity</h2>
<p>One important point here is that we have chosen <mark>granularity to be 3 digits</mark> in the ICD-10 code.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>We have already truncated the codes at 3 digit level while preparing the data.</p>
</div></div></section>
<section id="retain-top-n-empirical-covariates" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="retain-top-n-empirical-covariates">Retain top n empirical covariates</h2>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-11_3594b14d9aa15d11f86093f905bda9c4">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(autoCovariateSelection)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>step1 <span class="ot">&lt;-</span> <span class="fu">get_candidate_covariates</span>(<span class="at">df =</span> dfx,  </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">domainVarname =</span> <span class="st">"domain"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">eventCodeVarname =</span> <span class="st">"icd10"</span>, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">patientIdVarname =</span> <span class="st">"idx"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">patientIdVector =</span> patientIds,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">n =</span> <span class="dv">200</span>, </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">min_num_patients =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>You can use <code>autoCovariateSelection</code> package to implement these restrictions.</p>
</div></div><section id="long-format-data" class="level3">
<h3 class="anchored" data-anchor-id="long-format-data">Long format data</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-12_0ef9ae3ae7169fbfcde6e9d3e1159895">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>out1 <span class="ot">&lt;-</span> step1<span class="sc">$</span>covars_data</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(out1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     idx  icd10
1 100001 dx_M79
2 100001 dx_F32
3 100001 dx_R12
4 100001 dx_M79
5 100001 dx_K21
6 100001 dx_I10</code></pre>
</div>
</div>
</section>
<section id="updated-frequency-data" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="updated-frequency-data">Updated frequency data</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-13_4372035a7a12e0996db25c2c016206d8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">icd10 =</span> <span class="fu">names</span>(<span class="fu">table</span>(out1<span class="sc">$</span>icd10)),</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">count =</span> <span class="fu">as.numeric</span>(<span class="fu">table</span>(out1<span class="sc">$</span>icd10))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-14_c3af2f3a94a4ee9604aa1978a2b7e43a">
<div class="cell-output-display">

<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> ICD10 Code </th>
   <th style="text-align:right;"> Count </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> dx_A49 </td>
   <td style="text-align:right;"> 44 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> dx_B00 </td>
   <td style="text-align:right;"> 35 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> dx_B20 </td>
   <td style="text-align:right;"> 44 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> dx_B35 </td>
   <td style="text-align:right;"> 41 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> dx_B37 </td>
   <td style="text-align:right;"> 20 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> dx_B96 </td>
   <td style="text-align:right;"> 30 </td>
  </tr>
</tbody>
</table>

</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Only first few code frequencies are shown (alphabetic order), that were selected based on the restrictions <code>n</code> = 200 and <code>min_num_patients</code> = 20.</p>
</div></div><div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-15_9923195d04e3768fa35e9383d62cb530">
<div class="cell-output-display">

<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">  </th>
   <th style="text-align:left;"> ICD10 Code </th>
   <th style="text-align:right;"> Count </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 121 </td>
   <td style="text-align:left;"> dx_R73 </td>
   <td style="text-align:right;"> 431 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 122 </td>
   <td style="text-align:left;"> dx_T14 </td>
   <td style="text-align:right;"> 167 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 123 </td>
   <td style="text-align:left;"> dx_T78 </td>
   <td style="text-align:right;"> 201 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 124 </td>
   <td style="text-align:left;"> dx_T88 </td>
   <td style="text-align:right;"> 23 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 125 </td>
   <td style="text-align:left;"> dx_Z79 </td>
   <td style="text-align:right;"> 489 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 126 </td>
   <td style="text-align:left;"> dx_Z95 </td>
   <td style="text-align:right;"> 26 </td>
  </tr>
</tbody>
</table>

</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Only last few code frequencies are shown (alphabetic order).</p>
</div></div></section>
<section id="total-number-of-codes-retained" class="level3">
<h3 class="anchored" data-anchor-id="total-number-of-codes-retained">Total number of codes retained</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-16_b36bc268f179c581f081f7bb5768baf6">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 126</code></pre>
</div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-17_308aa3c45ccac9cb991b26400f534ee8">

</div>
</section>
</section>
</section>
<section id="step-3-recurrence" class="level1 page-columns page-full">
<h1>Step 3: Recurrence</h1>
<section id="genrate-recurrence-covariates" class="level2">
<h2 class="anchored" data-anchor-id="genrate-recurrence-covariates">Genrate recurrence covariates</h2>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-18_3ccf42bc4779d52ec1d70f101b1e2902">

</div>
<p>In this step, we generate <mark>3 binary recurrence covariates</mark> for each of the candidate empirical covariates identified in the previous step:</p>
<ul>
<li>occurred at least once</li>
<li>occurred sporadically (at least more than the median)</li>
<li>occurred frequently (at least more than the 75th percentile)</li>
</ul>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-19_8128dfb190302d2ecde2f0c3b2e5e8bd">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>step2 <span class="ot">&lt;-</span> <span class="fu">get_recurrence_covariates</span>(<span class="at">df =</span> out1, </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">patientIdVarname =</span> <span class="st">"idx"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">eventCodeVarname =</span> <span class="st">"icd10"</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">patientIdVector =</span> patientIds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="example-of-recurrence-covariates" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="example-of-recurrence-covariates">Example of recurrence covariates</h2>

<style>
  table {
    border-collapse: collapse;
    width: 100%;
  }
  
  th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
  }

  tr:nth-child(odd) {
    background-color: #f2f2f2;
  }

  tr:nth-child(even) td:nth-child(1){
    background-color: #f2f2f2;
  }
  
  th {
    border-top: 1px solid #ddd;
    border-bottom: 1px solid #ddd;
  }
</style>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>ICD-10-CM code (dimension 1)</th>
<th>code appeared at least once</th>
<th>code appeared at least more than the median</th>
<th>code appeared at least more than the 75th percentile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>D64.9</strong> Anemia</td>
<td>rec_dx_D64_once</td>
<td>rec_dx_D64_sporadic</td>
<td>rec_dx_D64_frequent</td>
</tr>
<tr class="even">
<td><strong>D75.9P</strong> Blood clots</td>
<td>rec_dx_D75_once</td>
<td>rec_dx_D75_sporadic</td>
<td>rec_dx_D75_frequent</td>
</tr>
<tr class="odd">
<td><strong>D89.9</strong> Immune disorder</td>
<td>rec_dx_D89_once</td>
<td>rec_dx_D89_sporadic</td>
<td>rec_dx_D89_frequent</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\ldots\)</span></td>
</tr>
<tr class="odd">
<td><strong>E07.9</strong> Disorder of thyroid</td>
<td>rec_dx_E07_once</td>
<td>rec_dx_E07_sporadic</td>
<td>rec_dx_E07_frequent</td>
</tr>
</tbody>
</table>

<div class="no-row-height column-margin column-container"><div class="">
<p>Example of 3 binary covariates (hypothetical) created based on the candidate empirical covariates.</p>
</div></div></section>
<section id="recurrence-covariates-in-the-data" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="recurrence-covariates-in-the-data">Recurrence covariates in the data</h2>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-20_53c9a80eb9dbc21d9e1d650d479ac2c6">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>out2 <span class="ot">&lt;-</span> step2<span class="sc">$</span>recurrence_data</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(out2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 143</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(out2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "idx"                 "rec_dx_A49_once"     "rec_dx_B00_once"    
  [4] "rec_dx_B20_once"     "rec_dx_B20_frequent" "rec_dx_B35_once"    
  [7] "rec_dx_B37_once"     "rec_dx_B96_once"     "rec_dx_C50_once"    
 [10] "rec_dx_D75_once"     "rec_dx_E03_once"     "rec_dx_E04_once"    
 [13] "rec_dx_E05_once"     "rec_dx_E07_once"     "rec_dx_E28_once"    
 [16] "rec_dx_E28_frequent" "rec_dx_E29_once"     "rec_dx_E78_once"    
 [19] "rec_dx_E79_once"     "rec_dx_E87_once"     "rec_dx_F17_once"    
 [22] "rec_dx_F20_once"     "rec_dx_F20_frequent" "rec_dx_F29_once"    
 [25] "rec_dx_F31_once"     "rec_dx_F31_frequent" "rec_dx_F32_once"    
 [28] "rec_dx_F39_once"     "rec_dx_F41_once"     "rec_dx_F43_once"    
 [31] "rec_dx_F90_once"     "rec_dx_G20_once"     "rec_dx_G20_frequent"
 [34] "rec_dx_G25_once"     "rec_dx_G30_once"     "rec_dx_G30_frequent"
 [37] "rec_dx_G31_once"     "rec_dx_G40_once"     "rec_dx_G43_once"    
 [40] "rec_dx_G47_once"     "rec_dx_G89_once"     "rec_dx_H04_once"    
 [43] "rec_dx_H10_once"     "rec_dx_H40_once"     "rec_dx_H40_frequent"
 [46] "rec_dx_H57_once"     "rec_dx_H57_frequent" "rec_dx_H66_once"    
 [49] "rec_dx_I10_once"     "rec_dx_I10_frequent" "rec_dx_I20_once"    
 [52] "rec_dx_I21_once"     "rec_dx_I48_once"     "rec_dx_I48_frequent"
 [55] "rec_dx_I49_once"     "rec_dx_I50_once"     "rec_dx_I50_frequent"
 [58] "rec_dx_I51_once"     "rec_dx_I63_once"     "rec_dx_I70_once"    
 [61] "rec_dx_I80_once"     "rec_dx_I99_once"     "rec_dx_J01_once"    
 [64] "rec_dx_J02_once"     "rec_dx_J20_once"     "rec_dx_J30_once"    
 [67] "rec_dx_J40_once"     "rec_dx_J42_once"     "rec_dx_J43_once"    
 [70] "rec_dx_J43_frequent" "rec_dx_J44_once"     "rec_dx_J44_frequent"
 [73] "rec_dx_J45_once"     "rec_dx_J45_frequent" "rec_dx_J98_once"    
 [76] "rec_dx_K04_once"     "rec_dx_K08_once"     "rec_dx_K21_once"    
 [79] "rec_dx_K25_once"     "rec_dx_K27_once"     "rec_dx_K30_once"    
 [82] "rec_dx_K31_once"     "rec_dx_K58_once"     "rec_dx_K59_once"    
 [85] "rec_dx_K76_once"     "rec_dx_K92_once"     "rec_dx_L08_once"    
 [88] "rec_dx_L20_once"     "rec_dx_L23_once"     "rec_dx_L29_once"    
 [91] "rec_dx_L40_once"     "rec_dx_L70_once"     "rec_dx_L93_once"    
 [94] "rec_dx_L93_frequent" "rec_dx_M06_once"     "rec_dx_M06_frequent"
 [97] "rec_dx_M10_once"     "rec_dx_M13_once"     "rec_dx_M19_once"    
[100] "rec_dx_M1A_once"     "rec_dx_M25_once"     "rec_dx_M54_once"    
[103] "rec_dx_M62_once"     "rec_dx_M79_once"     "rec_dx_M81_once"    
[106] "rec_dx_N19_once"     "rec_dx_N20_once"     "rec_dx_N28_once"    
[109] "rec_dx_N30_once"     "rec_dx_N32_once"     "rec_dx_N39_once"    
[112] "rec_dx_N40_once"     "rec_dx_N42_once"     "rec_dx_N52_once"    
[115] "rec_dx_N92_once"     "rec_dx_N94_once"     "rec_dx_N95_once"    
[118] "rec_dx_R00_once"     "rec_dx_R05_once"     "rec_dx_R06_once"    
[121] "rec_dx_R07_once"     "rec_dx_R09_once"     "rec_dx_R10_once"    
[124] "rec_dx_R11_once"     "rec_dx_R12_once"     "rec_dx_R19_once"    
[127] "rec_dx_R21_once"     "rec_dx_R25_once"     "rec_dx_R32_once"    
[130] "rec_dx_R35_once"     "rec_dx_R39_once"     "rec_dx_R41_once"    
[133] "rec_dx_R42_once"     "rec_dx_R45_once"     "rec_dx_R51_once"    
[136] "rec_dx_R52_once"     "rec_dx_R60_once"     "rec_dx_R73_once"    
[139] "rec_dx_T14_once"     "rec_dx_T78_once"     "rec_dx_T88_once"    
[142] "rec_dx_Z79_once"     "rec_dx_Z95_once"    </code></pre>
</div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-21_0c5a3608de945d9ad8adc36a812b8ca1">
<div class="cell-output cell-output-stdout">
<pre><code>     rec_dx_B20_once rec_dx_B20_frequent
6317               1                   1
6889               1                   0
6980               1                   1
7007               1                   0
7409               1                   0
7461               1                   1</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Here we show <mark>binary recurrence covariates</mark> for only 2 columns</p>
</div></div></section>
<section id="refined-recurrence-covariates" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="refined-recurrence-covariates">Refined recurrence covariates</h2>
<p>Below you can click to see a list of all recurrence covariates obtained in our data.</p>

<button onclick="toggleTable()">
Show/Hide Table
</button>
<div class="toggle-table" style="display:none">
<div class="cell-output-display">
<table class="table">
<caption>ICD-10 Recurrence Data</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: center;">rec_dx_A49_once</td>
<td style="text-align: center;">rec_dx_B00_once</td>
<td style="text-align: center;">rec_dx_B20_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: center;">rec_dx_B20_frequent</td>
<td style="text-align: center;">rec_dx_B35_once</td>
<td style="text-align: center;">rec_dx_B37_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: center;">rec_dx_B96_once</td>
<td style="text-align: center;">rec_dx_C50_once</td>
<td style="text-align: center;">rec_dx_D75_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: center;">rec_dx_E03_once</td>
<td style="text-align: center;">rec_dx_E04_once</td>
<td style="text-align: center;">rec_dx_E05_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: center;">rec_dx_E07_once</td>
<td style="text-align: center;">rec_dx_E28_once</td>
<td style="text-align: center;">rec_dx_E28_frequent</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: center;">rec_dx_E29_once</td>
<td style="text-align: center;">rec_dx_E78_once</td>
<td style="text-align: center;">rec_dx_E79_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: center;">rec_dx_E87_once</td>
<td style="text-align: center;">rec_dx_F17_once</td>
<td style="text-align: center;">rec_dx_F20_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: center;">rec_dx_F20_frequent</td>
<td style="text-align: center;">rec_dx_F29_once</td>
<td style="text-align: center;">rec_dx_F31_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: center;">rec_dx_F31_frequent</td>
<td style="text-align: center;">rec_dx_F32_once</td>
<td style="text-align: center;">rec_dx_F39_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: center;">rec_dx_F41_once</td>
<td style="text-align: center;">rec_dx_F43_once</td>
<td style="text-align: center;">rec_dx_F90_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: center;">rec_dx_G20_once</td>
<td style="text-align: center;">rec_dx_G20_frequent</td>
<td style="text-align: center;">rec_dx_G25_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: center;">rec_dx_G30_once</td>
<td style="text-align: center;">rec_dx_G30_frequent</td>
<td style="text-align: center;">rec_dx_G31_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: center;">rec_dx_G40_once</td>
<td style="text-align: center;">rec_dx_G43_once</td>
<td style="text-align: center;">rec_dx_G47_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: center;">rec_dx_G89_once</td>
<td style="text-align: center;">rec_dx_H04_once</td>
<td style="text-align: center;">rec_dx_H10_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: center;">rec_dx_H40_once</td>
<td style="text-align: center;">rec_dx_H40_frequent</td>
<td style="text-align: center;">rec_dx_H57_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: center;">rec_dx_H57_frequent</td>
<td style="text-align: center;">rec_dx_H66_once</td>
<td style="text-align: center;">rec_dx_I10_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: center;">rec_dx_I10_frequent</td>
<td style="text-align: center;">rec_dx_I20_once</td>
<td style="text-align: center;">rec_dx_I21_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: center;">rec_dx_I48_once</td>
<td style="text-align: center;">rec_dx_I48_frequent</td>
<td style="text-align: center;">rec_dx_I49_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: center;">rec_dx_I50_once</td>
<td style="text-align: center;">rec_dx_I50_frequent</td>
<td style="text-align: center;">rec_dx_I51_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: center;">rec_dx_I63_once</td>
<td style="text-align: center;">rec_dx_I70_once</td>
<td style="text-align: center;">rec_dx_I80_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">21</td>
<td style="text-align: center;">rec_dx_I99_once</td>
<td style="text-align: center;">rec_dx_J01_once</td>
<td style="text-align: center;">rec_dx_J02_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">22</td>
<td style="text-align: center;">rec_dx_J20_once</td>
<td style="text-align: center;">rec_dx_J30_once</td>
<td style="text-align: center;">rec_dx_J40_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">23</td>
<td style="text-align: center;">rec_dx_J42_once</td>
<td style="text-align: center;">rec_dx_J43_once</td>
<td style="text-align: center;">rec_dx_J43_frequent</td>
</tr>
<tr class="even">
<td style="text-align: left;">24</td>
<td style="text-align: center;">rec_dx_J44_once</td>
<td style="text-align: center;">rec_dx_J44_frequent</td>
<td style="text-align: center;">rec_dx_J45_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">25</td>
<td style="text-align: center;">rec_dx_J45_frequent</td>
<td style="text-align: center;">rec_dx_J98_once</td>
<td style="text-align: center;">rec_dx_K04_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">26</td>
<td style="text-align: center;">rec_dx_K08_once</td>
<td style="text-align: center;">rec_dx_K21_once</td>
<td style="text-align: center;">rec_dx_K25_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">27</td>
<td style="text-align: center;">rec_dx_K27_once</td>
<td style="text-align: center;">rec_dx_K30_once</td>
<td style="text-align: center;">rec_dx_K31_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">28</td>
<td style="text-align: center;">rec_dx_K58_once</td>
<td style="text-align: center;">rec_dx_K59_once</td>
<td style="text-align: center;">rec_dx_K76_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">29</td>
<td style="text-align: center;">rec_dx_K92_once</td>
<td style="text-align: center;">rec_dx_L08_once</td>
<td style="text-align: center;">rec_dx_L20_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: center;">rec_dx_L23_once</td>
<td style="text-align: center;">rec_dx_L29_once</td>
<td style="text-align: center;">rec_dx_L40_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">31</td>
<td style="text-align: center;">rec_dx_L70_once</td>
<td style="text-align: center;">rec_dx_L93_once</td>
<td style="text-align: center;">rec_dx_L93_frequent</td>
</tr>
<tr class="even">
<td style="text-align: left;">32</td>
<td style="text-align: center;">rec_dx_M06_once</td>
<td style="text-align: center;">rec_dx_M06_frequent</td>
<td style="text-align: center;">rec_dx_M10_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">33</td>
<td style="text-align: center;">rec_dx_M13_once</td>
<td style="text-align: center;">rec_dx_M19_once</td>
<td style="text-align: center;">rec_dx_M1A_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">34</td>
<td style="text-align: center;">rec_dx_M25_once</td>
<td style="text-align: center;">rec_dx_M54_once</td>
<td style="text-align: center;">rec_dx_M62_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">35</td>
<td style="text-align: center;">rec_dx_M79_once</td>
<td style="text-align: center;">rec_dx_M81_once</td>
<td style="text-align: center;">rec_dx_N19_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">36</td>
<td style="text-align: center;">rec_dx_N20_once</td>
<td style="text-align: center;">rec_dx_N28_once</td>
<td style="text-align: center;">rec_dx_N30_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">37</td>
<td style="text-align: center;">rec_dx_N32_once</td>
<td style="text-align: center;">rec_dx_N39_once</td>
<td style="text-align: center;">rec_dx_N40_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">38</td>
<td style="text-align: center;">rec_dx_N42_once</td>
<td style="text-align: center;">rec_dx_N52_once</td>
<td style="text-align: center;">rec_dx_N92_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">39</td>
<td style="text-align: center;">rec_dx_N94_once</td>
<td style="text-align: center;">rec_dx_N95_once</td>
<td style="text-align: center;">rec_dx_R00_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">40</td>
<td style="text-align: center;">rec_dx_R05_once</td>
<td style="text-align: center;">rec_dx_R06_once</td>
<td style="text-align: center;">rec_dx_R07_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">41</td>
<td style="text-align: center;">rec_dx_R09_once</td>
<td style="text-align: center;">rec_dx_R10_once</td>
<td style="text-align: center;">rec_dx_R11_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">42</td>
<td style="text-align: center;">rec_dx_R12_once</td>
<td style="text-align: center;">rec_dx_R19_once</td>
<td style="text-align: center;">rec_dx_R21_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">43</td>
<td style="text-align: center;">rec_dx_R25_once</td>
<td style="text-align: center;">rec_dx_R32_once</td>
<td style="text-align: center;">rec_dx_R35_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">44</td>
<td style="text-align: center;">rec_dx_R39_once</td>
<td style="text-align: center;">rec_dx_R41_once</td>
<td style="text-align: center;">rec_dx_R42_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">45</td>
<td style="text-align: center;">rec_dx_R45_once</td>
<td style="text-align: center;">rec_dx_R51_once</td>
<td style="text-align: center;">rec_dx_R52_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">46</td>
<td style="text-align: center;">rec_dx_R60_once</td>
<td style="text-align: center;">rec_dx_R73_once</td>
<td style="text-align: center;">rec_dx_T14_once</td>
</tr>
<tr class="odd">
<td style="text-align: left;">47</td>
<td style="text-align: center;">rec_dx_T78_once</td>
<td style="text-align: center;">rec_dx_T88_once</td>
<td style="text-align: center;">rec_dx_Z79_once</td>
</tr>
<tr class="even">
<td style="text-align: left;">48</td>
<td style="text-align: center;">rec_dx_Z95_once</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>

<script>
function toggleTable() {
  var x = document.getElementsByClassName("toggle-table")[0];
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Given that we had one dimension of proxy data, <span class="math inline">\(p=1\)</span>, at most <span class="math inline">\(n=200\)</span> most prevalent codes (with the restriction that minimum number of patients in each code = 20), and <span class="math inline">\(3\)</span> intensity, we could theoretically have at most <span class="math inline">\(p \times n \times 3 = 1 \times 200 \times \ 3 = 600\)</span> recurrence covariates.</li>
</ul>
</div>
</div>
<ul>
<li>Based on all of the restrictions, we created <mark>143 distinct recurrence covariates</mark>.</li>
<li>The merged data (analytic and proxies) size is now 7,585.</li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<ul>
<li>If 2 or all 3 recurrence covariates are identical, only <mark>one distinct recurrence covariate</mark> is returned. This is why you do not see any sporadic recurrence covariate here.</li>
<li>Recurrence covariate creation is for each patient, and it is possible to have same code occur multiple time because we are working with a 3 digit granularity (possible to have medications from other codes within same ICD-10 3 digit granularity).</li>
</ul>
</div></div><div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-23_39d0e98b7c1f6639dc1851bd84ae33da">

</div>
</section>
</section>
<section id="step-4-prioritize" class="level1 page-columns page-full">
<h1>Step 4: Prioritize</h1>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-24_b92b26cd015b1faad8accdd1c2cba087">

</div>
<section id="bross-formula" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="bross-formula">Bross formula</h2>
<p>We need to make an educated guess about 3 components (i.e., <mark>make an assumption</mark>), that are used in the calculation of <mark>bias contributed by not adjusting for a covariate</mark> based on <a href="https://pubmed.ncbi.nlm.nih.gov/5966011/">Bross (1966)</a> formula:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Bross formula for the Bias Multiplier considers both the imbalance in the prevalence of the unmeasured confounder between the exposure groups and the association between the confounder and the outcome to assess the potential bias.</p>
</div></div><ul>
<li>prevalence of a binary unmeasured confounder (<span class="math inline">\(U\)</span>) among exposed (<span class="math inline">\(P_{UA_1}\)</span>)</li>
<li>prevalence of that binary unmeasured confounder among unexposed (<span class="math inline">\(P_{UA_0}\)</span>)</li>
<li>association between that binary unmeasured confounder and the outcome (<span class="math inline">\(RR_{UY} = \frac{P_{UY_1}}{P_{UY_1}}\)</span>)</li>
</ul>
<p>The above components can help us calculate <span class="math inline">\(bias\)</span> amount (known as <mark>‘Bias Multiplier’</mark>) using the Bross formula when we omit adjusting for <span class="math inline">\(U\)</span>:</p>
<p><span class="math display">\[\text{Bias}_U = \frac{P_{UA_1} (RR_{UY} - 1) + 1}{P_{UA_0} (RR_{UY} - 1) + 1}\]</span></p>

<div class="no-row-height column-margin column-container"><div class="">
<p>These are the ingredients of the Bross formula. This formula is helpful for understanding the impact of unmeasured confounding of a binary variable. We have to put assumed prevalence and risk ratio associated with an unmeasured confounder.</p>
</div></div></section>
<section id="calculating-bias-from-a-recurrence-covariate" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="calculating-bias-from-a-recurrence-covariate">Calculating bias from a recurrence covariate</h2>
<p>For recurrence covariates (<span class="math inline">\(R\)</span>), we do not need to assume, we just <mark>plug-in <span class="math inline">\(R\)</span> instead of <span class="math inline">\(U\)</span></mark> in the following calculations:</p>
<ul>
<li>prevalence of a binary recurrence variable among exposed (<span class="math inline">\(P_{RA_1}\)</span>)</li>
<li>prevalence of that binary recurrence variable among unexposed (<span class="math inline">\(P_{RA_0}\)</span>)</li>
<li>association between that binary recurrence variable and the outcome (<span class="math inline">\(RR_{RY} = \frac{P_{RY_1}}{P_{RY_1}}\)</span>)</li>
</ul>
<p>These components can help us empirically calculate <span class="math inline">\(bias\)</span> amount:</p>
<p><span class="math display">\[\text{Bias}_R = \frac{P_{RA_1} (RR_{RY} - 1) + 1}{P_{RA_0} (RR_{RY} - 1) + 1}\]</span></p>
<p>Here, <span class="math inline">\(RR_{RY}\)</span> is the crude risk ratio between the recurrence covariate and the outcome, <span class="math inline">\(Y\)</span> is the outcome, <span class="math inline">\(A\)</span> is the exposure, and <span class="math inline">\(R\)</span> is a recurrence covariate.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>For recurrence covariates, we do not need to assume, we can basically calculate these numbers (<span class="math inline">\(log-absolute-bias\)</span>) for all of the recurrence covariates. For each data dimension, we can rank each of the recurrence covariates based on the amount of bias (confounding or imbalance) it could likely adjust.</p>
</div></div></section>
<section id="calculating-bias-from-all-recurrence-covariates" class="level2">
<h2 class="anchored" data-anchor-id="calculating-bias-from-all-recurrence-covariates">Calculating bias from all recurrence covariates</h2>
<p>In our example, we simply plug-in each recurrence covariates one-by-one to calculate <span class="math inline">\(log-absolute-bias\)</span>:</p>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-25_0127af1e969b0e39394e64f6e6f576bd">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<tbody>
<tr class="odd">
<td style="text-align: center;">R=rec_dx_D64_once</td>
</tr>
<tr class="even">
<td style="text-align: center;">R=rec_dx_D75_sporadic</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">R=rec_dx_E07_frequent</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="obtain-log-of-absolute-bias" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="obtain-log-of-absolute-bias">Obtain log of absolute-bias</h2>
<p>We calculate <span class="math inline">\(log-absolute-bias\)</span> for all recurrence covariates.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Absolute log of the Bias Multiplier, <span class="math inline">\(log-absolute-bias\)</span>, is a symmetric measure of the potential bias introduced by the recurrence covariate, making it easier to compare and rank recurrence covariates.</p>
</div></div><div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-26_a8ed41025ba0b1e22e1ae050b06399ac">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>out3 <span class="ot">&lt;-</span> <span class="fu">get_prioritised_covariates</span>(<span class="at">df =</span> out2,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">patientIdVarname =</span> <span class="st">"idx"</span>, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">exposureVector =</span> basetable<span class="sc">$</span>exposure,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">outcomeVector =</span> basetable<span class="sc">$</span>outcome,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">patientIdVector =</span> patientIds, </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">k =</span> <span class="dv">100</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>sorted_values <span class="ot">&lt;-</span> <span class="fu">sort</span>(out3<span class="sc">$</span>multiplicative_bias, </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This would return absolute log of the multiplicative bias for each recurrence covariate (by univariate Bross formula). We can use this information to prioritize recurrence covariates in the next step.</p>
</section>
<section id="convert-to-absolute-log-of-multiplicative-bias" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="convert-to-absolute-log-of-multiplicative-bias">Convert to Absolute log of multiplicative bias</h2>
<p>Here are the few covariates and associated Absolute log of the multiplicative bias:</p>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-27_a68600c15b4454aef2969921e1c8ffdc">
<div class="cell-output-display">

<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:center;">  </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:center;"> rec_dx_I10_once : 0.115 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> rec_dx_R73_once : 0.088 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> rec_dx_I10_frequent : 0.068 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> rec_dx_R60_once : 0.054 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> rec_dx_E78_once : 0.038 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> rec_dx_M79_once : 0.017 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> rec_dx_E87_once : 0.015 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> rec_dx_I51_once : 0.013 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> rec_dx_I50_once : 0.011 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>And here are translated table with description:</p>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-28_8fe93606588815e1b19128ae75cc3e1d">
<div class="cell-output-display">

<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:center;">  </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:center;"> Hypertension : 0.115 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> Elevated blood glucose level : 0.088 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> Hypertension : 0.068 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> Edema : 0.054 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> Pure hypercholesterolemia : 0.038 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> musculoskeletal pain : 0.017 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> Hypokalemia : 0.015 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> Heart disease : 0.013 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> Heart failure : 0.011 </td>
  </tr>
</tbody>
</table>

</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Some of the empirical covariates with top Absolute log of the multiplicative bias are actually relevant to the outcome (diabetes): Hypertension, Elevated blood glucose level , etc.</p>
</div></div><div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
SMD vs Bias multiplier
</div>
</div>
<div class="callout-body-container callout-body">
<p>Standardized mean difference (SMD) is useful for assessing the balance in the propensity score literature. However, Bross formula incorporates outcome information. In the investigation of empirical covariates or recurrence covariates where interpretations of these covariates are unknown, it may seem more safe to use the multiplicative bias term from the Bross formula to identify proxy covariates that are helpful in predicting the outcome.</p>
</div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-29_c578245ae44656e9f6396392b6af8040">

</div>
</section>
</section>
<section id="step-5-covariates" class="level1 page-columns page-full">
<h1>Step 5: Covariates</h1>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-30_9b8ee96571cc38a157ee7ec5095214d9">

</div>
<p>We select 2 types of covariates for the next step (to analyze using propensity score or other alternative approaches):</p>
<section id="ideal-number-of-prioritised-covariates" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="ideal-number-of-prioritised-covariates">Ideal number of prioritised covariates</h2>
<p>Based on calculated <span class="math inline">\(log-absolute-bias\)</span>, we select top <code>k</code> recurrence covariates to be used in the hdPS analyses later.</p>
<p>We used <span class="math inline">\(k = 100\)</span> covariates selected by the hdPS algorithm (we call them ‘hdPS covariates’). <mark>What should be the cutpoint?</mark></p>

<div class="no-row-height column-margin column-container"><div class="">
<ul>
<li>Absolute log of the Bias Multiplier has a null value of 0. Anything above 0 is an indication of confounding bias adjusted by the adjustment of the associated recurrent covariate.</li>
<li>For large proxy data sources, <span class="math inline">\(k = 500\)</span> is suggested.</li>
<li>See <a href="sens.qmd">Sensitivity Analysis</a> section for an understanding of how to choose a value based on an ad-hoc process.</li>
</ul>
</div></div></section>
<section id="selected-hdps-variables-proxies" class="level2">
<h2 class="anchored" data-anchor-id="selected-hdps-variables-proxies">Selected hdPS variables (proxies)</h2>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-31_dfc53d9b71f72cf665df2cb7066c4d46">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>hdps.dim <span class="ot">&lt;-</span> out3<span class="sc">$</span>autoselected_covariate_df</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(hdps.dim) <span class="co"># id + k</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7585  101</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hdps.dim)[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     idx rec_dx_I10_once rec_dx_R73_once
1 100001               1               0
2 100008               1               0
3 100012               1               0
4 100015               0               0
5 100018               0               0
6 100020               1               1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>hdps.dim<span class="sc">$</span>id <span class="ot">&lt;-</span> hdps.dim<span class="sc">$</span>idx</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>hdps.dim<span class="sc">$</span>idx <span class="ot">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="investigator-specified-covariates" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="investigator-specified-covariates">Investigator-specified covariates</h2>
<p><span class="math inline">\(25\)</span> investigator-specified covariates are selected based on variables in the DAG that are available in the data set.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>We should also add necessary interactions of these investigator-specified covariates, or add other useful model-specifications (e.g., polynomials).</p>
</div><div class="">
<ul>
<li>14 demographic, behavioral, health history related variables/access
<ul>
<li>Mostly <strong>categorical</strong></li>
</ul></li>
<li>11 lab variables
<ul>
<li>Mostly <strong>continuous</strong></li>
</ul></li>
</ul>
</div></div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-32_44eec29e2cd0f6f6bb097eefb4c8eb62">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>exposure <span class="ot">&lt;-</span> <span class="st">"obese"</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>outcome <span class="ot">&lt;-</span> <span class="st">"diabetes"</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>investigator.specified.covariates <span class="ot">&lt;-</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="co"># Demographic</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"age.cat"</span>, <span class="st">"sex"</span>, <span class="st">"education"</span>, <span class="st">"race"</span>, </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"marital"</span>, <span class="st">"income"</span>, <span class="st">"born"</span>, <span class="st">"year"</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># health history related variables/access</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"diabetes.family.history"</span>, <span class="st">"medical.access"</span>,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># behavioral</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"smoking"</span>, <span class="st">"diet.healthy"</span>, <span class="st">"physical.activity"</span>, <span class="st">"sleep"</span>,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Laboratory </span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"uric.acid"</span>, <span class="st">"protein.total"</span>, <span class="st">"bilirubin.total"</span>, <span class="st">"phosphorus"</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"sodium"</span>, <span class="st">"potassium"</span>, <span class="st">"globulin"</span>, <span class="st">"calcium.total"</span>, </span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"systolicBP"</span>, <span class="st">"diastolicBP"</span>, <span class="st">"high.cholesterol"</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(investigator.specified.covariates)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25</code></pre>
</div>
</div>
</section>
<section id="merged-data" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="merged-data">Merged data</h2>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-33_efed52ef5110cb5656561adb350ee007">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/analytic3cycles.RData"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>hdps.data <span class="ot">&lt;-</span> <span class="fu">merge</span>(data.complete[,<span class="fu">c</span>(<span class="st">"id"</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                                    outcome, </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                                    exposure, </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                                    investigator.specified.covariates)], </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                       hdps.dim, <span class="at">by =</span> <span class="st">"id"</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(hdps.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7585  128</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Variable count (128)</p>
<ul>
<li>1 ID variable</li>
<li>1 exposure</li>
<li>1 outcome</li>
<li>25 investigator-specified covariates</li>
<li>100 hdPS variables</li>
</ul>
</div></div><div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-34_87f59c0389dddaa1828d1a4eebc7fbda">

</div>
</section>
</section>
<section id="step-6-propensity" class="level1 page-columns page-full">
<h1>Step 6: Propensity</h1>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-35_cb911539114966da5baabcb32209e10f">

</div>
<section id="hdps-model" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="hdps-model">hdPS model</h2>

<div class="no-row-height column-margin column-container"><div class="">
<p>C = investigator-specified covariates and EC = hdPS covariates</p>
</div></div><p>Then the hdPS can be used as matching, weighting, stratifying variables, or as covariates (usually in deciles) in outcome model.</p>
<section id="create-propensity-score-formula" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="create-propensity-score-formula">Create propensity score formula</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-36_7e7038199fd59a1dfe20135fbb9c242a">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>hdps.data<span class="sc">$</span>exposure <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">I</span>(hdps.data<span class="sc">$</span>obese<span class="sc">==</span><span class="st">'Yes'</span>))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>hdps.data<span class="sc">$</span>outcome <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">I</span>(hdps.data<span class="sc">$</span>diabetes<span class="sc">==</span><span class="st">'Yes'</span>))</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>proxy.list.sel <span class="ot">&lt;-</span> <span class="fu">names</span>(out3<span class="sc">$</span>autoselected_covariate_df[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(proxy.list.sel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>proxyform <span class="ot">&lt;-</span> <span class="fu">paste0</span>(proxy.list.sel, <span class="at">collapse =</span> <span class="st">"+"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>covform <span class="ot">&lt;-</span> <span class="fu">paste0</span>(investigator.specified.covariates, <span class="at">collapse =</span> <span class="st">"+"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-37_343d756a47c46088c801a5ff6d50ce05">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>rhsformula <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">c</span>(covform, proxyform), <span class="at">collapse =</span> <span class="st">"+"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>ps.formula <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste0</span>(<span class="st">"exposure"</span>, <span class="st">"~"</span>, rhsformula))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>ps.formula</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>exposure ~ age.cat + sex + education + race + marital + income + 
    born + year + diabetes.family.history + medical.access + 
    smoking + diet.healthy + physical.activity + sleep + uric.acid + 
    protein.total + bilirubin.total + phosphorus + sodium + potassium + 
    globulin + calcium.total + systolicBP + diastolicBP + high.cholesterol + 
    rec_dx_I10_once + rec_dx_R73_once + rec_dx_I10_frequent + 
    rec_dx_R60_once + rec_dx_E78_once + rec_dx_M79_once + rec_dx_E87_once + 
    rec_dx_I51_once + rec_dx_I50_once + rec_dx_D75_once + rec_dx_K21_once + 
    rec_dx_Z79_once + rec_dx_N28_once + rec_dx_F41_once + rec_dx_E79_once + 
    rec_dx_M10_once + rec_dx_M1A_once + rec_dx_L70_once + rec_dx_F32_once + 
    rec_dx_I80_once + rec_dx_F90_once + rec_dx_F43_once + rec_dx_I50_frequent + 
    rec_dx_B00_once + rec_dx_R12_once + rec_dx_N19_once + rec_dx_B20_once + 
    rec_dx_E28_frequent + rec_dx_R07_once + rec_dx_M19_once + 
    rec_dx_I48_once + rec_dx_G47_once + rec_dx_T14_once + rec_dx_I70_once + 
    rec_dx_M06_once + rec_dx_N40_once + rec_dx_R51_once + rec_dx_R21_once + 
    rec_dx_J45_once + rec_dx_H40_once + rec_dx_K31_once + rec_dx_I63_once + 
    rec_dx_H10_once + rec_dx_R52_once + rec_dx_R19_once + rec_dx_N95_once + 
    rec_dx_K92_once + rec_dx_J20_once + rec_dx_E28_once + rec_dx_R32_once + 
    rec_dx_M13_once + rec_dx_G30_once + rec_dx_J98_once + rec_dx_N52_once + 
    rec_dx_I49_once + rec_dx_N30_once + rec_dx_N42_once + rec_dx_R39_once + 
    rec_dx_N92_once + rec_dx_B96_once + rec_dx_H40_frequent + 
    rec_dx_M54_once + rec_dx_K59_once + rec_dx_G25_once + rec_dx_F31_once + 
    rec_dx_T78_once + rec_dx_R41_once + rec_dx_G31_once + rec_dx_I99_once + 
    rec_dx_G30_frequent + rec_dx_C50_once + rec_dx_F39_once + 
    rec_dx_R06_once + rec_dx_F17_once + rec_dx_K30_once + rec_dx_R45_once + 
    rec_dx_K25_once + rec_dx_B37_once + rec_dx_L08_once + rec_dx_T88_once + 
    rec_dx_J42_once + rec_dx_R10_once + rec_dx_M06_frequent + 
    rec_dx_G20_once + rec_dx_E07_once + rec_dx_K58_once + rec_dx_R35_once + 
    rec_dx_K04_once + rec_dx_R05_once + rec_dx_K08_once + rec_dx_I20_once + 
    rec_dx_H57_once + rec_dx_R25_once + rec_dx_H66_once + rec_dx_R42_once + 
    rec_dx_B20_frequent + rec_dx_I48_frequent + rec_dx_M62_once + 
    rec_dx_G43_once + rec_dx_F29_once</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>This is an overly simplistic scenario where we are adding only the main effects in the non-transformed form.</p>
</div></div></section>
<section id="fit-ps-model" class="level3">
<h3 class="anchored" data-anchor-id="fit-ps-model">Fit PS model</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-38_e9a0f135215e3fbbbf3a1cb88a6edf7a">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(WeightIt)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>W.out <span class="ot">&lt;-</span> <span class="fu">weightit</span>(ps.formula, </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> hdps.data, </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">estimand =</span> <span class="st">"ATE"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">"ps"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="obtain-ps" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="obtain-ps">Obtain PS</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-39_815f2751cb283adda830bf389b6248fc">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>hdps.data<span class="sc">$</span>ps <span class="ot">&lt;-</span> W.out<span class="sc">$</span>ps</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-40_3bbed091f11703afdf0b9c35e9f6e5ae">
<div class="cell-output-display">
<p><img src="4a-hdps_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Always a good idea to check propensity score overlap in both exposure groups</p>
</div></div></section>
<section id="obtain-weights" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="obtain-weights">Obtain Weights</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-41_42d409347e99d2db5fa5997e4b8bf7aa">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>hdps.data<span class="sc">$</span>w <span class="ot">&lt;-</span> W.out<span class="sc">$</span>weights</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-42_d8255393bbb64c284c3ba9244999d9d1">
<div class="cell-output-display">
<p><img src="4a-hdps_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Always a good idea to check the summary statistics of the weights to assess whether there are extreme weights</p>
</div></div></section>
<section id="assessing-balance" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="assessing-balance">Assessing balance</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-43_abfd0ef7e060684111343af3d3e0a88a">
<div class="cell-output-display">
<p><img src="4a-hdps_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="480"></p>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Always a good idea to assess balance. Here we are measuring against SMD 0.1. Use <code>love.plot</code> function from the <code>cobalt</code> package. See more descriptions of balanced diagnostics <a href="https://ehsanx.github.io/psw/balance.html">elsewhere</a> for a propensity score context.</p>
</div></div><div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-44_1e130b32cdf6264764e313246cc586a7">

</div>
</section>
</section>
</section>
<section id="step-7-association" class="level1 page-columns page-full">
<h1>Step 7: Association</h1>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-45_5785b68f4a644933f7dba9f64691158d">

</div>
<section id="set-outcome-formula" class="level3">
<h3 class="anchored" data-anchor-id="set-outcome-formula">Set outcome formula</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-46_a9786e3805d27347b9c4a6a39c448b9d">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>out.formula <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste0</span>(<span class="st">"outcome"</span>, <span class="st">"~"</span>, <span class="st">"exposure"</span>))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>out.formula</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>outcome ~ exposure</code></pre>
</div>
</div>
</section>
<section id="obtain-or-from-unadjusted-model" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="obtain-or-from-unadjusted-model">Obtain OR from unadjusted model</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-47_768a9b4921524e246cfe8826231aa923">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(out.formula,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> hdps.data,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">weights =</span> W.out<span class="sc">$</span>weights,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">family=</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>fit.summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit)<span class="sc">$</span>coef[<span class="st">"exposure"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>                                 <span class="fu">c</span>(<span class="st">"Estimate"</span>, </span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Std. Error"</span>, </span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Pr(&gt;|z|)"</span>)]</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>fit.ci <span class="ot">&lt;-</span> <span class="fu">confint</span>(fit, <span class="at">level =</span> <span class="fl">0.95</span>)[<span class="st">"exposure"</span>, ]</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>fit.summary_with_ci <span class="ot">&lt;-</span> <span class="fu">c</span>(fit.summary, fit.ci)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">t</span>(<span class="fu">round</span>(fit.summary_with_ci,<span class="dv">2</span>))) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">Pr(&gt;|z|)</th>
<th style="text-align: right;">2.5 %</th>
<th style="text-align: right;">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">0.47</td>
</tr>
</tbody>
</table>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<ul>
<li>We are using a crude outcome model here.</li>
<li>Somewhat controversial to adjust for all (investigator-specified and all 100 proxies) covariates.</li>
</ul>
</div></div></section>
<section id="obtain-rd-from-unadjusted-model" class="level3">
<h3 class="anchored" data-anchor-id="obtain-rd-from-unadjusted-model">Obtain RD from unadjusted model</h3>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-48_98b45acd917a99c3f23507670c696e5d">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(out.formula,</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> hdps.data,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">weights =</span> W.out<span class="sc">$</span>weights,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">family=</span> <span class="fu">gaussian</span>(<span class="at">link =</span> <span class="st">"identity"</span>))</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>fit.summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit)<span class="sc">$</span>coef[<span class="st">"exposure"</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>                                 <span class="fu">c</span>(<span class="st">"Estimate"</span>, </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Std. Error"</span>, </span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Pr(&gt;|t|)"</span>)]</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>fit.summary[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sandwich<span class="sc">::</span><span class="fu">sandwich</span>(fit)[<span class="dv">2</span>,<span class="dv">2</span>])</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(lmtest)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>conf.int <span class="ot">&lt;-</span> <span class="fu">confint</span>(fit, <span class="st">"exposure"</span>, <span class="at">level =</span> <span class="fl">0.95</span>, <span class="at">method =</span> <span class="st">"hc1"</span>)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>fit.summary <span class="ot">&lt;-</span> <span class="fu">c</span>(fit.summary, conf.int)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">t</span>(<span class="fu">round</span>(fit.summary, <span class="dv">2</span>))) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
<th style="text-align: right;">2.5 %</th>
<th style="text-align: right;">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.09</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-hash="4a-hdps_cache/html/unnamed-chunk-49_578a5deff65ec9b65b6f9fdb123f459b">

</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>