# Plasmode

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(SASxport)
require(DiagrammeR)
require(DiagrammeRsvg)
require(rsvg)
library(magrittr)
library(svglite)
library(png)
require(nhanesA)
require(survey)
require(Publish)
require(jtools)
require(knitr)
# install.packages(c('glm2', 'arm', 'lme4', 'epiDisplay', 'twang', 'gbm', 'latticeExtra'))
# install.packages(
#   "https://cran.r-project.org/src/contrib/Archive/Plasmode/Plasmode_0.1.0.tar.gz",
#   repos = NULL, type = "source"
# )
require(Plasmode)
```

# Load data


```{r, cache=TRUE, message=FALSE, warning=FALSE, echo=FALSE}
load(file = "data/MasterPlasmodeData.RData")
```



```{r, cache=TRUE}
table(full.data$exposure)/sum(table(full.data$exposure))
table(full.data$outcome)/sum(table(full.data$outcome))
# table(full.data$exposure[full.data$outcome == 0])/
#   sum(table(full.data$exposure[full.data$outcome == 0]))
# table(full.data$outcome[full.data$exposure == 0])/
#   sum(table(full.data$outcome[full.data$exposure == 0]))
length(demovars)
demoform
length(labvars.original) 
labvars.originalform
length(labvars)
labform
length(sel.proxy)
sel.proxy.form
length(proxy.list)
basicdata <- full.data[,c("id", 
                          demovars,
                          labvars.original)]
extendeddata <- full.data[,c("id", 
                             demovars,
                             labvars.original,
                             proxy.list)]
```

# Create simple count variable

```{r, cache=TRUE}
full.data$simple.count <- apply(full.data[sel.proxy], 1, sum)
summary(full.data$simple.count)
hist(full.data$simple.count)
```

# Setup formulas

```{r, cache=TRUE}
rhsformula <- paste0(c(demoform, labform, "simple.count"), collapse = "+")
rhsformula
```


```{r init1, eval=TRUE, cache=TRUE}
formulaOut <- as.formula(paste0("outcome ~ exposure +", rhsformula))
formulaOut
formulaExp <- as.formula(paste0("exposure ~ ", rhsformula))
formulaExp
```
# Initial plasmode

```{r, cache=TRUE}
require(Plasmode)
ss <- 4500
# from https://cran.r-project.org/src/contrib/Archive/Plasmode/Plasmode_0.1.0.tar.gz
set.seed(111)
simdata.obj0 <- PlasmodeBin(formulaOut=formulaOut,
                            formulaExp=formulaExp,
                            data=full.data,
                            idVar="id",
                            nsim=1,
                            size=ss, 
                            eventRate=NULL, 
                            exposedPrev=NULL)
kable(simdata.obj0$TrueOutBeta)
length(simdata.obj0$TrueOutBeta)
simdata.obj0$RR
simdata.obj0$RD
```
# Plasmode simulation (frequent outcome and exposure)

```{r, cache=TRUE}
nSim <- 1000
set.seed(111)
simdata.obj <- PlasmodeBin(formulaOut=formulaOut,
                           formulaExp=formulaExp,
                           data=full.data,
                           idVar="id",
                           effectOR =1,
                           nsim=nSim, 
                           size=ss, 
                           eventRate=0.3, 
                           exposedPrev=0.3,
                           MMOut = c(rep(1, length(simdata.obj0$TrueOutBeta)-2), 5))
simdata.obj$RR
simdata.obj$RD
```


```{r, cache=TRUE}
library(kableExtra)

# Stack and transpose coefficients
coef_table <- rbind(
  `Initial Plasmode (coef)` = simdata.obj0$TrueOutBeta,
  `Full Simulation (coef)`  = simdata.obj$TrueOutBeta
)
coef_table_t <- t(coef_table)

# Add exponentiated values as new columns
coef_table_full <- cbind(
  coef_table_t,
  `exp(Initial)` = exp(coef_table_t[, 1]),
  `exp(Full)`    = exp(coef_table_t[, 2])
)

# Round for display
coef_table_full <- round(coef_table_full, 3)

# Pretty HTML table
kable(coef_table_full, format = "html",
      caption = "Comparison of True Outcome Model Coefficients and Their Exponentiated Values") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                full_width = FALSE,
                position = "left") %>%
  row_spec(0, bold = TRUE, color = "white", background = "#2c3e50") %>%
  column_spec(1, bold = TRUE)


```


```{r, cache=TRUE}
simdata <- simdata.obj$Sim_Data 
```

# Save

```{r save, eval=TRUE, cache=TRUE}
saveRDS(simdata, file = "data/plasmode-freq-ID.RData")
```

# Plasmode simulation (exposure rare)

```{r, cache=TRUE}
set.seed(111)
simdata.objER <- PlasmodeBin(formulaOut=formulaOut,
                           formulaExp=formulaExp,
                           data=full.data,
                           idVar="id",
                           effectOR =1,
                           nsim=nSim, 
                           size=ss, 
                           eventRate=0.3, 
                           exposedPrev=0.1,
                           MMOut = c(rep(1, length(simdata.obj0$TrueOutBeta)-2), 5))
coef_table <- data.frame(
  Coefficient = round(simdata.objER$TrueOutBeta, 3),
  `exp(Coefficient)` = round(exp(simdata.objER$TrueOutBeta), 3)
)

# Print with kable
kable(coef_table, format = "html", caption = "True Outcome Model Coefficients and Exponentiated Values") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = FALSE,
                position = "left") %>%
  row_spec(0, bold = TRUE, background = "#2c3e50", color = "white")
simdata.objER$RR
simdata.objER$RD
```


```{r, cache=TRUE}
simdataER <- simdata.objER$Sim_Data 
```

# Save

```{r saveER, eval=TRUE, cache=TRUE}
saveRDS(simdataER, file = "data/plasmode-rareExp-ID.RData")
```




# Plasmode simulation (rare outcome)

```{r, cache=TRUE}
set.seed(111)
simdata.objOR <- PlasmodeBin(formulaOut=formulaOut,
                           formulaExp=formulaExp,
                           data=full.data,
                           idVar="id",
                           effectOR =1,
                           nsim=nSim, 
                           size=ss, 
                           eventRate=0.1, 
                           exposedPrev=0.3,
                           MMOut = c(rep(1, length(simdata.obj0$TrueOutBeta)-2), 5))
# Create a data frame with raw and exponentiated coefficients
coef_table <- data.frame(
  Coefficient = round(simdata.objOR$TrueOutBeta, 3),
  `exp(Coefficient)` = round(exp(simdata.objOR$TrueOutBeta), 3)
)

# Show with formatting
kable(coef_table, format = "html", caption = "True Outcome Model Coefficients and Exponentiated Values") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = FALSE,
                position = "left") %>%
  row_spec(0, bold = TRUE, background = "#2c3e50", color = "white")
simdata.objOR$RR
simdata.objOR$RD
```


```{r, cache=TRUE}
simdataOR <- simdata.objOR$Sim_Data 
```

# Save

```{r saveOR, eval=TRUE, cache=TRUE}
saveRDS(simdataOR, file = "data/plasmode-rareOut-ID.RData")
```

